### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by JakobDev** [marco-calautti/DeltaPatcher#39]
I created a [Flatpak](https://flathub.org) for DeltaPatcher. This allows easier installing on evry Linux Distro. Here is the Manifest:
```yaml
id: io.github.marco_calautti.DeltaPatcher
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: DeltaPatcher
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
  - --device=dri

modules:
  - name: DeltaPatcher
    buildsystem: cmake-ninja
    post-install:
      - install -Dm755 app/DeltaPatcher $FLATPAK_DEST/bin/DeltaPatcher
    sources:
      - type: git
        url: https://github.com/marco-calautti/DeltaPatcher.git
```
I shows a error but it works without any problems. It needs a few things before it can be fully released. tell me, if you are interested.

**Comment by marco-calautti** [comment]
That would be actually nice to have. I guess you need to add a .desktop file with the icon, and such. You can find the icons at different resolutions in the "graphics" directory in the repo. My only concern is support to the system theme. Delta Patcher supports light and dark modes, depending on the system settings. The flatpak should be configured properly so that Delta Patcher is able to use the right theme. Feel free to submit a pull request!

**Comment by marco-calautti** [comment]
Another thing I am not sure how will workout in Flatpak is the lack of portals. Delta Patcher does not make explicit use of portals, and so I am wondering how it can access files from the file system. I guess you need to specify the right filesystem permissions in the manifest (which are currently doing), but using "host" as filesystem permissions is maybe overkill. I guess "home" is a better option for Delta Patcher.

**Comment by JakobDev** [comment]
I have now created #40 for the data files. 

> My only concern is support to the system theme. Delta Patcher supports light and dark modes, depending on the system settings.

Looks like this is already supported by wxWidgets.

> Another thing I am not sure how will workout in Flatpak is the lack of portals.

Gtk has GtkFileChooserNative, which uses the Portals. I don't know much abou wxWidgets, but maybe you can use this function in the Gtk Backend.

You also need to fix this error, which appers on startup.
![grafik](https://github.com/marco-calautti/DeltaPatcher/assets/15185051/434bb228-5339-4da9-ab26-a824334e46d1)

**Comment by marco-calautti** [comment]
Of you are using the system's wxwidgets lib, then you will also get that error, as all binaroes of wxwidgets I am aware of in repositories are all compiled with assertions ON

**Comment by JakobDev** [comment]
When using `DCMAKE_BUILD_TYPE=RelWithDebInfo` the message no longer appears, but you should fix the underlying bug.

**Comment by marco-calautti** [comment]
I have just pushed a pull request that fixes the warnings. They should not appear anymore. Anyway, I think building in Release mode is still preferred, as this avoids wxWidgets countinuously calling its asserts, "slowing down" things.

**Comment by JakobDev** [comment]
> Anyway, I think building in Release mode is still preferred

It is usual to build a Flatpak with debug symbols, but you can change this if you really want it.

The only missing thing is now to use the Portals. If you don't know how to use Portals in wxWidgets, you can use zenity, whcih is preinstalled in the Flatpak Runtime. Just run `zenity --file-selection` to open a file dialog. You can use the `--file-filter` argument to add a filter.

Here is the current version of the Manifest:
```yaml
id: io.github.marco_calautti.DeltaPatcher
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: DeltaPatcher
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --filesystem=host
  - --device=dri
  - --device=dri

modules:
  - name: DeltaPatcher
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DwxBUILD_SHARED=OFF
    sources:
      - type: dir
        path: /path/to/source
```
Just set the path to the source directory of DeltaPatcher.

**Comment by marco-calautti** [comment]
I tried the manifest on my local machine, and portals are not required, assuming we give filesystem access (actually, Delta Patcher only requires home). I slightly modified the manifest to also allow the flatpak to have access to the current system gtk theme:
```yaml
id: io.github.marco_calautti.DeltaPatcher
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: DeltaPatcher
finish-args:
  - --socket=fallback-x11
  - --socket=wayland
  - --filesystem=home
  - --filesystem=xdg-config/gtk-3.0:ro
  - --device=dri
  - --device=dri

modules:
  - name: DeltaPatcher
    buildsystem: cmake-ninja
    config-opts:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DwxBUILD_SHARED=OFF
    sources:
      - type: dir
        path: /path/to/source```

**Comment by marco-calautti** [comment]
I will now create a new tag for the new version, and I guess you can submit the flatpak manifest to flathub referencing the new tag.

**Comment by marco-calautti** [comment]
https://github.com/marco-calautti/DeltaPatcher/releases/tag/v3.1.3

**Comment by JakobDev** [comment]
> portals are not required, assuming we give filesystem access

I don't said that it is not working with filesystem access. That's the reason my Manifest has Host access, but it would be better if Portals were used instead of this Permission.

>  (actually, Delta Patcher only requires home)

I would rather give host access. With home access Users can't open any files on external drives. Full home access aleady allows breaking the Sandbox, as you can edit e.g. .bashrc or startup files, so host access is not more insecure.

> and I guess you can submit the flatpak manifest to flathub referencing the new tag.

Yes. Use this as you source:
```yaml
- type: git
  url: https://github.com/marco-calautti/DeltaPatcher.git
  tag: 'v3.1.3'
  commit: 46011a90aade9c178020d9d5c96817b33c7b33c3
  x-checker-data:
    type: git
```
